@baseUrl = http://localhost:3333

# @name startProcess
POST {{baseUrl}}/make HTTP/1.1
Content-Type: application/json

{}

###

# Criar data para ser exportada
# @name getData
GET {{baseUrl}}/make HTTP/1.1
Content-Type: application/json

{}
