name: Build and Publish CLI

on:
    push:
        branches:
            - master
        paths:
            - 'src/**'
            - 'video/**'
            - 'assets/**'
    workflow_dispatch:

jobs:
    CacheDependencies:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.JS environment
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: 14.x

            - name: Cache node_modules
              id: dependencies
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

            - name: Install project dependencies
              if: steps.dependencies.outputs.cache-hit != 'true'
              run: yarn

    BuildAndPublish:
        needs: [CacheDependencies]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.JS environment
              uses: actions/setup-node@v2.1.4
              with:
                  node-version: 14.x

            - name: Get node_modules from cache
              id: dependencies
              uses: actions/cache@v2
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

            - name: Install project dependencies
              if: steps.dependencies.outputs.cache-hit != 'true'
              run: yarn

            - name: Publish
              run: yarn publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
